### ISSUE TITLE
Add support for RFC-3548 base32 key strings

### ISSUE THREAD

**Issue by hgfischer** [hgfischer/go-otp#1]
http://tools.ietf.org/html/rfc3548

**Comment by hgfischer** [comment]
Done, thanks to the help of @andyHa.

**Comment by andyHa** [comment]
Awesome! Thanks for keeping up the quality - and thanks for sharing the
code in the first place.

In case you (or any one else reading this) is wondering what I use this lib
for: https://github.com/scireum/hildeguard

It's a tool which supports TOTPs for SSH logins (while still supporting key
based login etc.)

freundliche Grüße
scireum GmbH

Andreas Haufler
Geschäftsführer

-------------------------------------------------------------------------------------------------------
scireum GmbH, Eisenbahnstr. 24, 73630 Remshalden

Unser Service - gerne für Sie da:
Vertrieb: (07151) 90316 10
Support: (07151) 90316 20 - E-Mail: support@scireum.net

Tel.: (07151) 90316 21 - E-Mail:  aha@scireum.de
Fax: (07151) 90316 19 - Internet: http://www.scireum.de

Geschäftsführer: Michael Haufler, Andreas Haufler
Amtsgericht Stuttgart, HRB 732171

2015-03-08 16:38 GMT+01:00 Herbert Fischer <notifications@github.com>:
